name: Build/deploy mlflow stack

on:
  push:
    paths:
      - container/**
  workflow_dispatch:

env:
  DEPLOYMENT_ROLE: "arn:aws:iam::562760952310:role/AWSGithubActionsRole"


permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install Python dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.DEPLOYMENT_ROLE }}
          aws-region: eu-central-1
      - name: cdk bootstrap mlflow stack
        run: |
            echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account | tr -d '"')" >> $GITHUB_ENV
            echo "AWS_REGION=$(aws configure get region)" >> $GITHUB_ENV
            cdk bootstrap aws://${ACCOUNT_ID}/${AWS_REGION}
      - name: cdk deploy mlflow stack
        run: cdk deploy --parameters ProjectName=mlflow --require-approval never
        working-directory: .

